# Generated by Django 5.0 on 2023-12-08 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('available_units', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('image', models.ImageField(blank=True, upload_to='menu_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.menuitem')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.purchase')),
            ],
        ),
        migrations.AddField(
            model_name='purchase',
            name='menu_items',
            field=models.ManyToManyField(through='main.PurchaseItem', to='main.menuitem'),
        ),
        migrations.CreateModel(
            name='RecipeRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredent_quantity', models.PositiveIntegerField()),
                ('ingredent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ingredent')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.menuitem')),
            ],
        ),
        migrations.AddField(
            model_name='menuitem',
            name='ingredents',
            field=models.ManyToManyField(through='main.RecipeRequirement', to='main.ingredent'),
        ),
    ]
