# Generated by Django 5.0 on 2023-12-09 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='menu_items',
            new_name='purchase_items',
        ),
    ]
